version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: user-service
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  wallet-service:
    build:
      context: .
      dockerfile: WalletService/Dockerfile
    container_name: wallet-service
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
